/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ReportController;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.jvnet.substance.skin.SubstanceEmeraldDuskLookAndFeel;
import org.jvnet.substance.skin.SubstanceMistAquaLookAndFeel;
import org.jvnet.substance.skin.SubstanceMistSilverLookAndFeel;
import org.jvnet.substance.skin.SubstanceRavenLookAndFeel;

/**
 *
 * @author Fadli Hudaya
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
        setExtendedState(6);
        reportController = new ReportController();
    }

    public void setActive(String level) {
        if (level.equals("Admin Keuangan")) {
            masterMenu.setEnabled(true);
            adminMenu.setEnabled(true);
            biayaOperasionalMenu.setEnabled(true);
            produkSewaMenu.setEnabled(true);
            laporanMenu.setEnabled(true);
            loginMenu.setText("Logout Admin");
            loginMenu.setText("Logout");
        } else {
            masterMenu.setEnabled(true);
            adminMenu.setEnabled(false);
            biayaOperasionalMenu.setEnabled(false);
            produkSewaMenu.setEnabled(false);
            loginMenu.setText("Logout Admin");
            loginMenu.setText("Logout");
        }
    }

    private void deactive() {
        masterMenu.setEnabled(false);
        laporanMenu.setEnabled(false);
        loginMenu.setText("Login");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new Fadly.CustomComponents.component.DesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        daftarMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        loginMenu = new javax.swing.JMenu();
        masterMenu = new javax.swing.JMenu();
        adminMenu = new javax.swing.JMenuItem();
        biayaOperasionalMenu = new javax.swing.JMenuItem();
        produkSewaMenu = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        Transaksi = new javax.swing.JMenuItem();
        laporanMenu = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIAK DIFAN");

        desktopPane.setGambar(new java.io.File("E:\\Git_Repos\\program_akuntansi\\src\\resources\\Tulips.jpg"));

        daftarMenu.setText("Daftar");

        jMenuItem1.setText("Perusahaan");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        daftarMenu.add(jMenuItem1);

        jMenuBar1.add(daftarMenu);

        loginMenu.setText("Login");
        loginMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(loginMenu);

        masterMenu.setText("Data Master");
        masterMenu.setEnabled(false);

        adminMenu.setText("Perusahaan");
        adminMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminMenuActionPerformed(evt);
            }
        });
        masterMenu.add(adminMenu);

        biayaOperasionalMenu.setText("Akun");
        biayaOperasionalMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biayaOperasionalMenuActionPerformed(evt);
            }
        });
        masterMenu.add(biayaOperasionalMenu);

        produkSewaMenu.setText("Produk Sewa");
        produkSewaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produkSewaMenuActionPerformed(evt);
            }
        });
        masterMenu.add(produkSewaMenu);

        jMenuItem2.setText("Pelanggan");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        masterMenu.add(jMenuItem2);

        Transaksi.setText("Transaksi");
        Transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransaksiActionPerformed(evt);
            }
        });
        masterMenu.add(Transaksi);

        jMenuBar1.add(masterMenu);

        laporanMenu.setText("Laporan");
        laporanMenu.setEnabled(false);

        jMenuItem5.setText("Laporan Produk Sewa");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        laporanMenu.add(jMenuItem5);

        jMenuItem6.setText("Laporan Pelanggan");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        laporanMenu.add(jMenuItem6);

        jMenuItem7.setText("Laporan Jurnal Umum");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        laporanMenu.add(jMenuItem7);

        jMenuItem8.setText("Laporan Buku Besar");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        laporanMenu.add(jMenuItem8);

        jMenuItem13.setText("Laporan Neraca Saldo Bulanan");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        laporanMenu.add(jMenuItem13);

        jMenuItem10.setText("Laporan Neraca Saldo Tahunan");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        laporanMenu.add(jMenuItem10);

        jMenuItem9.setText("Laporan Laba Rugi");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        laporanMenu.add(jMenuItem9);

        jMenuBar1.add(laporanMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void produkSewaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produkSewaMenuActionPerformed
        ProdukSewaView sv = new ProdukSewaView();
        desktopPane.removeAll();
        desktopPane.updateUI();
        desktopPane.add(sv);
        sv.setVisible(true);
    }//GEN-LAST:event_produkSewaMenuActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        PelangganView pv = new PelangganView();
        desktopPane.removeAll();
        desktopPane.updateUI();
        desktopPane.add(pv);
        pv.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void biayaOperasionalMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biayaOperasionalMenuActionPerformed
        AkunView bv = new AkunView();
        desktopPane.removeAll();
        desktopPane.updateUI();
        desktopPane.add(bv);
        bv.setVisible(true);
    }//GEN-LAST:event_biayaOperasionalMenuActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        reportController.getReportProduk();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        reportController.getReportPelanggan();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        PeriodeView pv = new PeriodeView(this, true, true);
        pv.setOption(1);
        pv.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        PeriodeView pv = new PeriodeView(this, true, true);
        pv.setOption(2);
        pv.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        PeriodeView pv = new PeriodeView(this, true, true);
        pv.setOption(3);
        pv.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void adminMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminMenuActionPerformed
        AdminView av = new AdminView();
        desktopPane.removeAll();
        desktopPane.add(av);
        desktopPane.updateUI();
        av.setVisible(true);
    }//GEN-LAST:event_adminMenuActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        PeriodeView pv = new PeriodeView(this, true, true);
        pv.setOption(4);
        pv.setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        PeriodeView pv = new PeriodeView(this, true, false);
        pv.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void loginMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMenuMouseClicked
        if (loginMenu.getText().equals("Login")) {
            LoginView lv = new LoginView(this, true, this);
            lv.setVisible(true);
        } else {
            deactive();
        }
    }//GEN-LAST:event_loginMenuMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        DaftarView dv = new DaftarView();
        desktopPane.removeAll();
        desktopPane.add(dv);
        desktopPane.updateUI();
        dv.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void TransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransaksiActionPerformed

    }//GEN-LAST:event_TransaksiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Transaksi;
    private javax.swing.JMenuItem adminMenu;
    private javax.swing.JMenuItem biayaOperasionalMenu;
    private javax.swing.JMenu daftarMenu;
    private Fadly.CustomComponents.component.DesktopPane desktopPane;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu laporanMenu;
    private javax.swing.JMenu loginMenu;
    private javax.swing.JMenu masterMenu;
    private javax.swing.JMenuItem produkSewaMenu;
    // End of variables declaration//GEN-END:variables
    private ReportController reportController;

    static {
        try {
            UIManager.setLookAndFeel(new SubstanceMistSilverLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MenuUtama.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
