/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ReportController;

/**
 *
 * @author Fadli Hudaya
 */
public class PeriodeView extends javax.swing.JDialog {

    /**
     * Creates new form PeriodeView
     */
    public PeriodeView(java.awt.Frame parent, boolean modal, boolean isBulanan) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.isBulanan = isBulanan;
        if (!this.isBulanan) {
            bulanField.setVisible(false);
        }
        reportController = new ReportController();
    }

    public void setOption(int option) {
        this.option = option;
    }

    private String parseMonth(Integer bulan) {
        String result = "";
        switch (bulan) {
            case 1:
                result = "January";
                break;
            case 2:
                result = "February";
                break;
            case 3:
                result = "March";
                break;
            case 4:
                result = "April";
                break;
            case 5:
                result = "May";
                break;
            case 6:
                result = "June";
                break;
            case 7:
                result = "July";
                break;
            case 8:
                result = "August";
                break;
            case 9:
                result = "September";
                break;
            case 10:
                result = "October";
                break;
            case 11:
                result = "November";
                break;
            case 12:
                result = "December";
                break;
            default:
                return null;
        }
        return result;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bulanField = new javax.swing.JComboBox();
        tahunField = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        baruButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bulanField.setFont(new java.awt.Font("Gill Sans MT", 0, 13)); // NOI18N
        bulanField.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));

        tahunField.setFont(new java.awt.Font("Gill Sans MT", 0, 13)); // NOI18N
        tahunField.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2015", "2016", "2017", "2018", "2019", "2020" }));

        jLabel2.setFont(new java.awt.Font("Gill Sans MT", 0, 13)); // NOI18N
        jLabel2.setText("Periode :");

        baruButton2.setFont(new java.awt.Font("Gill Sans MT", 0, 13)); // NOI18N
        baruButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/batal.png"))); // NOI18N
        baruButton2.setText("Cetak");
        baruButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baruButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(baruButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bulanField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tahunField, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bulanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tahunField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(baruButton2)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void baruButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baruButton2ActionPerformed
        this.dispose();
        if (isBulanan) {
            if (option == 1) {
                reportController.getReportJurnal(parseMonth(bulanField.getSelectedIndex() + 1), tahunField.getSelectedItem().toString());
            } else if (option == 2) {
                reportController.getReportBukuBesar(parseMonth(bulanField.getSelectedIndex() + 1), tahunField.getSelectedItem().toString());
            } else if (option == 3) {
                reportController.getReportLabaRugi(parseMonth(bulanField.getSelectedIndex() + 1), tahunField.getSelectedItem().toString());
            } else {
                reportController.getReportNeraca(parseMonth(bulanField.getSelectedIndex() + 1), tahunField.getSelectedItem().toString());
            }
        } else {
            reportController.getReportNeracaTahunan(tahunField.getSelectedItem().toString());
        }
    }//GEN-LAST:event_baruButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton baruButton;
    private javax.swing.JButton baruButton1;
    private javax.swing.JButton baruButton2;
    private javax.swing.JComboBox bulanField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox tahunField;
    // End of variables declaration//GEN-END:variables
    private ReportController reportController;
    private int option = 0;
    private boolean isBulanan;
}
